<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class post extends Model
{
    //
    public function categories(){
        return $this->belongsToMany('App\Models\category','category_posts')->withTimeStamps();
    }
    public function tags(){
        return $this->belongsToMany('App\Models\tag','post_tags')->withTimeStamps();
    }
    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

}
